version: '3.8'

services:
  app:
    build: ./
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - mynetwork
    restart: on-failure
    env_file:
      - .env
    environment:
      - APP_PORT=${APP_PORT}
      - CONNECTION_STRING=${CONNECTION_STRING}

networks:
  mynetwork:
    driver: bridge
    external: true