// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: auth.proto

package authService

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ValidateTokensRequest) Validate() error {
	return nil
}
func (this *ValidateTokensResponse) Validate() error {
	return nil
}
func (this *GenerateTokensRequest) Validate() error {
	return nil
}
func (this *GenerateTokensResponse) Validate() error {
	return nil
}
func (this *RefreshTokensRequest) Validate() error {
	return nil
}
func (this *RefreshTokensResponse) Validate() error {
	return nil
}
